//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Animalese_Generator.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Animalese_Generator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_A_56__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_A_56__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_A_58__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_A_58__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_A_60__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_A_60__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_A_62__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_A_62__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_A_64__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_A_64__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_A_66__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_A_66__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_A_68__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_A_68__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_A_70__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_A_70__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_A_72__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_A_72__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_E_56__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_E_56__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_E_58__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_E_58__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_E_60__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_E_60__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_E_62__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_E_62__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_E_64__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_E_64__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_E_66__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_E_66__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_E_68__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_E_68__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_E_70__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_E_70__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_E_72__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_E_72__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_I_56__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_I_56__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_I_58__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_I_58__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_I_60__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_I_60__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_I_62__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_I_62__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_I_64__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_I_64__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_I_66__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_I_66__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_I_68__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_I_68__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_I_70__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_I_70__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_I_72__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_I_72__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_O_56__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_O_56__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_O_58__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_O_58__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_O_60__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_O_60__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_O_62__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_O_62__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_O_64__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_O_64__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_O_66__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_O_66__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_O_68__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_O_68__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_O_70__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_O_70__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_O_72__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_O_72__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_U_56__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_U_56__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_U_58__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_U_58__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_U_60__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_U_60__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_U_62__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_U_62__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_U_64__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_U_64__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_U_66__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_U_66__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_U_68__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_U_68__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_U_70__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_U_70__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Boy_U_72__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Boy_U_72__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_A_56__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_A_56__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_A_58__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_A_58__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_A_60__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_A_60__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_A_62__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_A_62__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_A_64__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_A_64__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_A_66__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_A_66__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_A_68__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_A_68__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_A_70__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_A_70__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_A_72__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_A_72__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_E_56__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_E_56__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_E_58__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_E_58__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_E_60__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_E_60__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_E_62__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_E_62__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_E_64__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_E_64__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_E_66__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_E_66__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_E_68__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_E_68__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_E_70__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_E_70__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_E_72__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_E_72__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_I_56__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_I_56__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_I_58__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_I_58__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_I_60__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_I_60__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_I_62__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_I_62__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_I_64__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_I_64__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_I_66__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_I_66__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_I_68__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_I_68__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_I_70__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_I_70__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_I_72__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_I_72__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_O_56__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_O_56__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_O_58__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_O_58__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_O_60__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_O_60__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_O_62__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_O_62__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_O_64__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_O_64__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_O_66__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_O_66__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_O_68__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_O_68__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_O_70__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_O_70__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_O_72__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_O_72__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_U_56__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_U_56__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_U_58__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_U_58__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_U_60__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_U_60__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_U_62__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_U_62__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_U_64__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_U_64__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_U_66__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_U_66__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_U_68__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_U_68__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_U_70__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_U_70__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Girl_U_72__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Girl_U_72__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_A_56__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_A_56__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_A_58__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_A_58__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_A_60__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_A_60__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_A_62__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_A_62__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_A_64__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_A_64__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_A_66__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_A_66__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_A_68__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_A_68__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_A_70__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_A_70__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_A_72__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_A_72__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_E_56__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_E_56__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_E_58__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_E_58__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_E_60__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_E_60__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_E_62__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_E_62__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_E_64__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_E_64__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_E_66__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_E_66__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_E_68__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_E_68__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_E_70__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_E_70__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_E_72__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_E_72__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_I_56__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_I_56__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_I_58__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_I_58__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_I_60__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_I_60__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_I_62__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_I_62__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_I_64__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_I_64__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_I_66__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_I_66__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_I_68__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_I_68__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_I_70__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_I_70__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_I_72__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_I_72__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_O_56__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_O_56__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_O_58__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_O_58__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_O_60__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_O_60__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_O_62__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_O_62__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_O_64__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_O_64__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_O_66__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_O_66__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_O_68__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_O_68__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_O_70__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_O_70__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_O_72__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_O_72__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_U_56__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_U_56__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_U_58__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_U_58__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_U_60__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_U_60__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_U_62__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_U_62__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_U_64__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_U_64__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_U_66__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_U_66__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_U_68__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_U_68__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_U_70__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_U_70__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Npc_Vocal_Man_U_72__1_ {
            get {
                return ResourceManager.GetStream("Npc_Vocal_Man_U_72__1_", resourceCulture);
            }
        }
    }
}
